[2024-09-30T16:34:15.788+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-30T16:34:15.800+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT.fact_run.fact_2 manual__2024-09-30T16:34:13.596392+00:00 [queued]>
[2024-09-30T16:34:15.805+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT.fact_run.fact_2 manual__2024-09-30T16:34:13.596392+00:00 [queued]>
[2024-09-30T16:34:15.806+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-09-30T16:34:15.814+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): fact_run.fact_2> on 2024-09-30 16:34:13.596392+00:00
[2024-09-30T16:34:15.818+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2031) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-30T16:34:15.819+0000] {standard_task_runner.py:72} INFO - Started process 2037 to run task
[2024-09-30T16:34:15.821+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ELT', 'fact_run.fact_2', 'manual__2024-09-30T16:34:13.596392+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/load.py', '--cfg-path', '/tmp/tmpkuy7_6zk']
[2024-09-30T16:34:15.823+0000] {standard_task_runner.py:105} INFO - Job 48: Subtask fact_run.fact_2
[2024-09-30T16:34:15.874+0000] {task_command.py:467} INFO - Running <TaskInstance: ELT.fact_run.fact_2 manual__2024-09-30T16:34:13.596392+00:00 [running]> on host 51a7ea638889
[2024-09-30T16:34:15.925+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ELT' AIRFLOW_CTX_TASK_ID='fact_run.fact_2' AIRFLOW_CTX_EXECUTION_DATE='2024-09-30T16:34:13.596392+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-30T16:34:13.596392+00:00'
[2024-09-30T16:34:15.927+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-30T16:34:15.955+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-30T16:34:15.962+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-30T16:34:15.962+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=ELT, task_id=fact_run.fact_2, run_id=manual__2024-09-30T16:34:13.596392+00:00, execution_date=20240930T163413, start_date=20240930T163415, end_date=20240930T163415
[2024-09-30T16:34:16.001+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-30T16:34:16.011+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-30T16:34:16.012+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
